import 'package:tyrant_engine/src/model/dice.dart';
import 'package:tyrant_engine/src/model/weapon.dart';
import 'package:tyrant_engine/src/model/weapon_slot.dart';

//const longstrikeRailgun = Weapon(
//  name: 'Longstrike Railgun',
//  type: WeaponSlotType.railgun,
//  shieldBonus: -1,
//  armorBonus: 0,
//  hullBonus: 0,
//  crewBonus: 0,
//  damage: r1d6,
//  ru: 2,
//  heat: 1,
//  oht: 5,
//  range: 72,
//);

const lumencorpDisruptorV = Weapon(
    name: 'Lumencorp Disruptor V',
    type: WeaponSlotType.railgun,
    damage: r2d4,
    ru: 3,
    heat: 1,
    oht: 6,
    shieldBonus: 0,
    armorBonus: 0,
    hullBonus: 0,
    crewBonus: 0,
    range: 72,
    speed: null); // 1	1	-10	-5
const longstrikeRailgun = Weapon(
    name: 'Longstrike Railgun',
    type: WeaponSlotType.railgun,
    damage: r2d4,
    ru: 2,
    heat: 1,
    oht: 6,
    shieldBonus: 0,
    armorBonus: 2,
    hullBonus: 0,
    crewBonus: 0,
    range: 72,
    speed: null); // 0	0	-10	-5
const emPiercingRailgun = Weapon(
    name: 'EM Piercing Railgun',
    type: WeaponSlotType.railgun,
    damage: r1d6,
    ru: 2,
    heat: 2,
    oht: 6,
    shieldBonus: 6,
    armorBonus: 0,
    hullBonus: 0,
    crewBonus: 0,
    range: 72,
    speed: null); // 0	2	-10	-5
const militekDevastatorRailgun = Weapon(
    name: 'Militek Devastator Railgun',
    type: WeaponSlotType.railgun,
    damage: r1d8,
    ru: 5,
    heat: 2,
    oht: 7,
    shieldBonus: 0,
    armorBonus: 0,
    hullBonus: 3,
    crewBonus: 0,
    range: 72,
    speed: null); // 0	0	-10	-5
const hurukaiEradicatorRailgun = Weapon(
    name: 'Hurukai Eradicator Railgun',
    type: WeaponSlotType.railgun,
    damage: r2d8,
    ru: 7,
    heat: 5,
    oht: 5,
    shieldBonus: 0,
    armorBonus: 0,
    hullBonus: 0,
    crewBonus: 0,
    range: 84,
    speed: null); // 0	0	-10	-5
const darkwaterUltraVRailgun = Weapon(
    name: 'Darkwater Ultra V Railgun',
    type: WeaponSlotType.railgun,
    damage: r3d6,
    ru: 8,
    heat: 6,
    oht: 5,
    shieldBonus: 0,
    armorBonus: 0,
    hullBonus: 0,
    crewBonus: 4,
    range: 84,
    speed: null); // 0	0	-10	-5
const hurukaiHopliteV = Weapon(
    name: 'Hurukai Hoplite V',
    type: WeaponSlotType.autocannon,
    damage: r2d4,
    ru: 2,
    heat: 2,
    oht: 6,
    shieldBonus: 0,
    armorBonus: 1,
    hullBonus: 1,
    crewBonus: 0,
    range: 48,
    speed: null); // 0	0	-5	-2
const starforgeInterceptorIII = Weapon(
    name: 'Starforge Interceptor III ',
    type: WeaponSlotType.autocannon,
    damage: r1d8,
    ru: 4,
    heat: 3,
    oht: 7,
    shieldBonus: 0,
    armorBonus: 2,
    hullBonus: 1,
    crewBonus: 0,
    range: 48,
    speed: null); // 0	0	-5	-2
const darkwaterDeepImpact = Weapon(
    name: 'Darkwater Deep Impact ',
    type: WeaponSlotType.autocannon,
    damage: r2d8,
    ru: 5,
    heat: 5,
    oht: 5,
    shieldBonus: 0,
    armorBonus: 0,
    hullBonus: 2,
    crewBonus: 0,
    range: 48,
    speed: null); // 0	0	-5	-2
const militekThunderchildV = Weapon(
    name: 'Militek Thunderchild V ',
    type: WeaponSlotType.autocannon,
    damage: r3d8,
    ru: 7,
    heat: 6,
    oht: 4,
    shieldBonus: 0,
    armorBonus: 2,
    hullBonus: 3,
    crewBonus: 0,
    range: 48,
    speed: null); // 0	0	-5	-2
const fdEclipticAc4400 = Weapon(
    name: 'FD Ecliptic AC4400 ',
    type: WeaponSlotType.autocannon,
    damage: r3d10,
    ru: 7,
    heat: 7,
    oht: 3,
    shieldBonus: 0,
    armorBonus: 0,
    hullBonus: 0,
    crewBonus: 4,
    range: 48,
    speed: null); // 0	0	-5	-2
const hurukaiPdcII = Weapon(
    name: 'Hurukai PDC II',
    type: WeaponSlotType.chaingun,
    damage: r2d4,
    ru: 1,
    heat: 2,
    oht: 5,
    shieldBonus: 0,
    armorBonus: 1,
    hullBonus: 3,
    crewBonus: 0,
    range: 18,
    speed: null); // 0	0	3	5
const militekLightMarkVChaingun = Weapon(
    name: 'Militek Light Mark V Chaingun',
    type: WeaponSlotType.chaingun,
    damage: r2d6,
    ru: 1,
    heat: 3,
    oht: 5,
    shieldBonus: 1,
    armorBonus: 2,
    hullBonus: 3,
    crewBonus: 1,
    range: 18,
    speed: null); // 0	0	3	5
const darkwaterRelentlessIIChaingun = Weapon(
    name: 'Darkwater Relentless II Chaingun',
    type: WeaponSlotType.chaingun,
    damage: r4d4,
    ru: 2,
    heat: 3,
    oht: 4,
    shieldBonus: 0,
    armorBonus: 0,
    hullBonus: 4,
    crewBonus: 1,
    range: 18,
    speed: null); // 0	0	3	5
const hurukaiHullbreakerIChaingun = Weapon(
    name: 'Hurukai Hullbreaker I Chaingun',
    type: WeaponSlotType.chaingun,
    damage: r3d6,
    ru: 3,
    heat: 5,
    oht: 4,
    shieldBonus: 0,
    armorBonus: 0,
    hullBonus: 5,
    crewBonus: 2,
    range: 18,
    speed: null); // 0	0	3	5
const darkwaterRelentlessVChaingun = Weapon(
    name: 'Darkwater Relentless V Chaingun',
    type: WeaponSlotType.chaingun,
    damage: r5d6,
    ru: 3,
    heat: 6,
    oht: 1,
    shieldBonus: 0,
    armorBonus: 0,
    hullBonus: 0,
    crewBonus: 3,
    range: 18,
    speed: null); // 0	0	3	5
const militekStandardMissile = Weapon(
    name: 'Militek Standard Missile',
    type: WeaponSlotType.missile,
    damage: r2d8,
    ru: 4,
    heat: 0,
    oht: 2,
    shieldBonus: -2,
    armorBonus: 0,
    hullBonus: 3,
    crewBonus: 1,
    range: null,
    speed: 18); // 8	0	1	0	1
const ironGuardEmpMissile = Weapon(
    name: 'IronGuard EMP Missile',
    type: WeaponSlotType.missile,
    damage: r2d10,
    ru: 5,
    heat: 0,
    oht: 2,
    shieldBonus: 10,
    armorBonus: 0,
    hullBonus: 0,
    crewBonus: 0,
    range: null,
    speed: 18); // 8	0	0	0	1
const armorPiercingMissile = Weapon(
    name: 'Armor-Piercing Missile',
    type: WeaponSlotType.missile,
    damage: r3d6,
    ru: 6,
    heat: 0,
    oht: 2,
    shieldBonus: -2,
    armorBonus: 0,
    hullBonus: 4,
    crewBonus: 1,
    range: null,
    speed: 18); // 8	0	0	0	1
const emberClusterMissile = Weapon(
    name: 'Ember Cluster Missile',
    type: WeaponSlotType.missile,
    damage: r4d8,
    ru: 8,
    heat: 1,
    oht: 2,
    shieldBonus: 0,
    armorBonus: 0,
    hullBonus: 0,
    crewBonus: 0,
    range: null,
    speed: 18); // 	0	0	0	1
const quantumMissile = Weapon(
    name: 'Quantum Missile',
    type: WeaponSlotType.missile,
    damage: r3d12,
    ru: 7,
    heat: 1,
    oht: 1,
    shieldBonus: -2,
    armorBonus: 0,
    hullBonus: 0,
    crewBonus: 6,
    range: null,
    speed: 18); // 8	0	0	0	1
const vortexMissileCluster = Weapon(
    name: 'Vortex Missile Cluster',
    type: WeaponSlotType.missile,
    damage: r3d4,
    ru: 8,
    heat: 0,
    oht: 2,
    shieldBonus: -2,
    armorBonus: 0,
    hullBonus: 6,
    crewBonus: 1,
    range: null,
    speed: 20); // 0	3	3	0	1
const militekHunterV = Weapon(
    name: 'Militek Hunter V',
    type: WeaponSlotType.torpedo,
    damage: r6d6,
    ru: 8,
    heat: 1,
    oht: 1,
    shieldBonus: -5,
    armorBonus: 10,
    hullBonus: 10,
    crewBonus: 1,
    range: null,
    speed: 12); // 	12	0	0	0	0
const militekHellfireBeta = Weapon(
    name: 'Militek Hellfire Beta',
    type: WeaponSlotType.torpedo,
    damage: r6d6,
    ru: 7,
    heat: 1,
    oht: 1,
    shieldBonus: -5,
    armorBonus: 5,
    hullBonus: 5,
    crewBonus: 0,
    range: null,
    speed: 12); // 2	0	0	0	0
const darkwaterPacer = Weapon(
    name: 'Darkwater Pacer',
    type: WeaponSlotType.torpedo,
    damage: r3d10,
    ru: 7,
    heat: 1,
    oht: 1,
    shieldBonus: -5,
    armorBonus: 10,
    hullBonus: 10,
    crewBonus: 0,
    range: null,
    speed: 24); // 	24	0	0	0	0
const fdArgonaughtIII = Weapon(
    name: 'FD Argonaught III',
    type: WeaponSlotType.torpedo,
    damage: r4d10,
    ru: 8,
    heat: 1,
    oht: 1,
    shieldBonus: -5,
    armorBonus: -10,
    hullBonus: 10,
    crewBonus: 10,
    range: null,
    speed: 12); // 00	12	0	0	0	0
const starforgeHorizonVIII = Weapon(
    name: 'Starforge Horizon VIII',
    type: WeaponSlotType.torpedo,
    damage: r4d12,
    ru: 8,
    heat: 2,
    oht: 1,
    shieldBonus: -10,
    armorBonus: -15,
    hullBonus: -15,
    crewBonus: -15,
    range: null,
    speed: 10); // 5	100	10	3	3	0	0;
